<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /* @var $block \MageWorx\AlsoBought\Block\System\Config\Apply */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var applySpan = jQuery('#apply_span');

        jQuery('#apply_button').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    applySpan.find('.applied').hide();
                    applySpan.find('.processing').show();
                    jQuery('#apply_message_span').text('');
                },
                onSuccess: function(response) {

                    console.log(response);

                    applySpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        applySpan.find('.applied').show();
                    }
                    jQuery('#apply_message_span').text(resultText);

                    var json = response.responseJSON;
                    if (typeof json.time != 'undefined') {
                        jQuery('#row_mageworx_alsobought_general_apply_time').find('.value .time').text(json.time);
                    }

                }
            });
        });

    });
</script>
<?php echo $block->getButtonHtml() ?>
<span class="apply-indicator" id="apply_span">
    <img class="processing" hidden="hidden" alt="Applying" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="applied" hidden="hidden" alt="Applied" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="apply_message_span"></span>
</span>
